### ISSUE TITLE
[epic] vinyl-fs version 3.0.0

### ISSUE THREAD

**Issue by phated** [gulpjs/gulp#1604]
I'm creating this issue to get some more visibility on outstanding issues in vinyl-fs for it to reach 3.0 (which we'd like to ship with gulp 4).

If you are able to tackle any of these, the help would be very much appreciated.
- [x] ~~Decouple opening and closing of file descriptors from src and dest - gulpjs/vinyl-fs#158~~
- [x] ~~Support changing uid/gid from the vinyl object to the file on disk - gulpjs/vinyl-fs#157~~
- [x] ~~Support setting setuid/setgid/sticky bits - gulpjs/vinyl-fs#156~~
- [x] ~~Support functions for all options - gulpjs/vinyl-fs#139~~
- [x] ~~kebabCase the filenames - gulpjs/vinyl-fs#152~~
- [x] ~~vfs.dest(outfolder, { base.. }) ignores outfolder? - gulpjs/vinyl-fs#141~~
- [x] ~~The mkdirp module doesn't handle modes in the best way - gulpjs/vinyl-fs#165~~
- [x] ~~Account for process.umask - gulpjs/vinyl-fs#166~~
- [x] ~~Test refactor - gulpjs/vinyl-fs#194~~
- [x] ~~Separate `prepareWrite` into own module - gulpjs/vinyl-fs#193~~
- [x] ~~Fix Symlink TODOs (issues need to be created)~~
- [x] ~~Sink the symlink stream - gulpjs/vinyl-fs#195~~
- [x] ~~Get https://github.com/gulpjs/vinyl-sourcemap up-to-snuff~~
- [x] Rebase vinyl-fs to generate conventional changelog (https://github.com/gulpjs/vinyl-fs/issues/284)
- [x] Finalize documentation

**Comment by phated** [comment]
Updated! We've had some excellent contributions by @hgwood and @tmcgee123
Some of the improvements brought to light a couple of other things we need help with.

**Comment by ChALkeR** [comment]
Note that `vinyl-fs@0.3.14` will stop working with Node.js 7.0, as it includes `graceful-fs@1.2.3`:
```
└─┬ gulp@3.9.1
  └─┬ vinyl-fs@0.3.14
    └─┬ glob-watcher@0.0.6
      └─┬ gaze@0.5.2
        └─┬ globule@0.1.0
          └─┬ glob@3.1.21
            └── graceful-fs@1.2.3
```

See https://github.com/gulpjs/gulp/issues/1571 for more details.

**Comment by ChALkeR** [comment]
Ah, no, I can't comment there.

The thing is, 
> There is nothing wrong with the dependency, especially since it is only used in development. 

is invalid. The deprecation warning is emitted by Node.js only in those situations that would cause a throw in Node.js 7.0. Just running latest stable `gulp` with an empty gulpfile emits a warning — that means that it will throw.

**Comment by ChALkeR** [comment]
Tracking issue: https://github.com/nodejs/node/issues/5213 (to get a status badge there).

**Comment by phated** [comment]
Almost all these are wrapping up.  We need to get some more tests in place for the changes and solidify the "Support functions for all options" stuff.

Still looking for someone to tackle the uid/gid stuff.

**Comment by odino** [comment]
What about a smaller update to vinyl? With this issue on minimatch everyone gets lots of [sec. alerts](https://nodesecurity.io/advisories/118) :)

**Comment by phated** [comment]
@odino no, those alerts don't matter. If you are passing user input directly to gulp, you have bigger problems.

**Comment by odino** [comment]
That's true, but those alerts will keep coming due to gulp requiring the
library. So even if this has never been exploited people are gonna
"wtf?!?!" anyway unless they really dig into it and figure out that this is
not an issue at all.

If there's an easy way to upgrade to a version that has the patch I would
suggest to go for it, else if its a big PITA then never mind :)

**Comment by strugee** [comment]
@phated the UID/GID item should be checked off, no?

**Comment by ilanbiala** [comment]
@phated any update on ^^?

**Comment by atomantic** [comment]
re @odino and security fix. this could be fixed just by updating the version of vinyl-fs that gulp installs. Currently you get `vinyl-fs@^0.3.0` which translates to a really old version of vinyl.

This is a problem for anyone requiring `nsp check` to pass for a build to succeed.

**Comment by Den-dp** [comment]
> this could be fixed just by updating the version of vinyl-fs

@atomantic a lot of things was changed since vinyl-fs@0.3.14 https://github.com/gulpjs/vinyl-fs/blob/master/CHANGELOG.md#v0314-20150921-2357-0000 so it is impossible just bump the version.
In fact, migration to vinyl-fs@3.0.0 is a thing and the whole point of this issue.

**Comment by phated** [comment]
@strugee @ilanbiala thanks, I've updated the list. However, a few more things had to be added to account for things I've found during the test refactor.

**Comment by atomantic** [comment]
got it. Yeah, I noticed tests pass as long as I upgrade vinyl-fs to latest version and include glob-watcher 0.0.8--but that's still a really old version of glob-watcher. `glob-watcher@3.0.0` has some differences that break it.

**Comment by phated** [comment]
@atomantic the gulp tests are just a smoke test because each underlying library has a full test suite that we aren't going to duplicate.  Extreme amounts of stuff has changed and you should not assume everything will __just work__.

**Comment by phated** [comment]
I've submitted the test refactor for review at https://github.com/gulpjs/vinyl-fs/pull/194 - I'd like to get feedback before I push it so feel free to comment.

**Comment by pgilad** [comment]
Hey - any news on this? `gulp` is bringing in an outdated version of `minimatch` (with security issues)..

**Comment by phated** [comment]
@pgilad I'm pretty diligent about updating this thread when there are updates, so no.  You can follow the linked issues to see progress on the outstanding items (and even contribute).  The minimatch warning you mention doesn't mean anything because you aren't passing raw user input to the gulp methods (or you shouldn't be).

**Comment by addyosmani** [comment]
@phated First, thanks for all the awesome contributions you continue to make to Gulp. Second, looking at the `prepareWrite` note it appears this is done as of https://github.com/gulpjs/vinyl-fs/commit/cc99707d7acd832af91ca0823bd5fa6388bef168 and the associated tests also landed. Was there more work to do before it could be checked off the list?

**Comment by phated** [comment]
@addyosmani unfortunately that commit didn't solve everything and caused problems with the symlink method so it was never merged. There are some more option normalizations that are in progress, so I have been focusing on the glob-stream and vinyl dependencies.

**Comment by haoranw** [comment]
thanks for your contributions

**Comment by abhijeetkpawar** [comment]
This epic is taking epic time to resolve :(

**Comment by strugee** [comment]
@abhijeetkpawar everyone working on Gulp is a volunteer. If you want it to go faster, you are welcome to volunteer as well.

**Comment by phated** [comment]
We've also just received https://github.com/gulpjs/vinyl-sourcemap as a dependency for vinyl-fs.  There's still plenty of work to be done on it so any little bit helps.

**Comment by mcdado** [comment]
I'm not that experienced, but I'd love to help.
I see that there are some points still unchecked. Any suggestions to which to roll up my sleeves at first, be it by priority or accessibility? (this last term used very vaguely, forgive me)

**Comment by nhaglind** [comment]
Running node v.7.1.0 and npm 4.0.2 and receiving an error when running `gulp` 
```
Error: Cannot find module 'internal/fs'
at Object.<anonymous> (node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1) 

```

**Comment by strugee** [comment]
@nhaglind please don't comment on random issues with (somewhat) unrelated problems.

Normally I'd tell you to file a new issue, but it would just be a duplicate of #1571 anyway.

**Comment by kyleholzinger** [comment]
Agreed @mcdado! I'd love to help in any way I can, any low hanging fruit that's just kind of tedious work for me to do? I just want to help out any way I can :)

**Comment by strugee** [comment]
@phated in the interest of Gulp 4 hitting npm sooner, couldn't some of these issues be pushed past the release? E.g. supporting functions for all options and separating `prepareWrite` into a separate module don't _seem_ like semver-major changes (although I of course am not an expert). This is especially relevant given that Node 7 is now released and breaking Gulp 3 installs left and right.

**Comment by phated** [comment]
@strugee no, that's a breaking change. This list is breaking change exclusive and everything else is being pushed.  Feel free to contribute on the issues.

**Comment by strugee** [comment]
@phated ah, okay. I still don't see how, but I'll take your word for it :)

Thanks for the quick response.

**Comment by phated** [comment]
I need some help writing tests for https://github.com/gulpjs/glob-stream/pull/85 if anyone is interested.

**Comment by kyleholzinger** [comment]
I'd be down to help out @phated !

**Comment by phated** [comment]
@kyleholzinger awesome!  shoot me a PR on the glob-stream repository when you have some tests.  Many thanks!

**Comment by kyleholzinger** [comment]
Will do

**Comment by chipironcin** [comment]
Chiming in here, I just got a warning message from `graceful-fs`:
>graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.

Tracking it down:

```
├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     ├─┬ glob@3.1.21
│   │     │ ├── graceful-fs@1.2.3
```

If we don't update to vinyl v3, then graceful-fs won't be updated to 4.1.10 therefore gulp will not be compatible with Node >=7.0

**Comment by hgwood** [comment]
@chipironcin This is not the issue you are looking for. Please see https://github.com/gulpjs/gulp/issues/1571. `graceful-fs` 1.x is fine, it works on Node 7. Only 2.x and 3.0-3.9 are problematic.

**Comment by chipironcin** [comment]
Thanks for the response @hgwood 
I though any version would be problematic as it says:
>graceful-fs v3.0.0 and before
And I am actually getting the warning so `graceful-fs 1.x` may not be fine. If it works, then the message from `graceful-fs` is wrong :P

**Comment by CKGrafico** [comment]
Is this the last thing before the release?

**Comment by phated** [comment]
@CKGrafico this issue is the largest remaining change for the release. There might be small stuff sprinkled around (we've been labeling everything with "help wanted")

**Comment by CKGrafico** [comment]
Thanks @phated seems [not a lot of work ](https://github.com/gulpjs/gulp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+label%3Agulp4)I will try to help with something, the community needs this release :)

**Comment by phated** [comment]
Thanks but we have many issues opened throughout the organization. 

You can see everything labeled as "help wanted" at https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Agulpjs+label%3A%22help+wanted%22+

We are tackling some of them this weekend at HackIllinois

**Comment by CKGrafico** [comment]
Amazing work, I'll wait to next week. Good luck at HackIllinois

**Comment by phated** [comment]
This is getting really close.  I need help with https://github.com/gulpjs/vinyl-sourcemap/issues/19

**Comment by black-snow** [comment]
Will this incorporate a vinyl-fs update? Following the dep tree there's a graceful-fs@1.2.3 dependency which warns me with *graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in
 the tree.*

**Comment by anru** [comment]
Any progress on this ? Looks like almost things from list are already done. May be I can help somehow ?

gulp still have very old vinyl-fs dependency, and I get following warning each time I install/upgrade gulp:
`npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible`

├─┬ gulp@3.9.1
│ └─┬ vinyl-fs@0.3.14
│   ├─┬ glob-watcher@0.0.6
│   │ └─┬ gaze@0.5.2
│   │   └─┬ globule@0.1.0
│   │     └─┬ glob@3.1.21
│   │       └── graceful-fs@1.2.3

**Comment by kyleholzinger** [comment]
@anru If you check out [that link phated posted](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+org%3Agulpjs+label%3A%22help+wanted%22+) there's a bunch of issues left in the org, I think those are all related to the upgrade

**Comment by mcdado** [comment]
@anru I believe the roadmap is here: https://github.com/gulpjs/gulp/issues/1945

More than the warning the main issue of the current version is the incompatibility with Node > 6. Later this year 8 will be LTS and then it will become more problematic to have gulp as a dependency.

I previously said I'm willing to help, I'll probably take a look at doc related issues.

**Comment by anru** [comment]
#1945 is gulp **4** roadmap. And may be we could release gulp 3 with updated `vinyl-fs` dependency. Or is it will be more simple to help with gulp 4 where is `vinul-fs` already updated. What will be more quick/easy ?
I'm asking because there are no incomplete issues in issue description, except `Fix Symlink TODOs (issues need to be created)`

**Comment by strugee** [comment]
@anru @mcdado see #1571. The gulp team is aware of the graceful-fs problems, but it's impossible to upgrade Vinyl without breaking changes. Hence, gulp 4.

**Comment by subesokun** [comment]
Any updates on this? The NSP check fails on all my projects which are using Gulp when scanning also dev dependencies :(

**Comment by errorx666** [comment]
@subesokun
It seems like that vulnerability requires an attacker to be able to pass an arbitrary glob string to minimatch... which seems like a bad idea in general.

**Comment by kyleholzinger** [comment]
Is the "Fix Symlink TODOs (issues need to be created)" item the only thing that's left to do here?

**Comment by phated** [comment]
@kyleholzinger yes, it is a tough problem we are trying to solve over on the vinyl-fs repo.

**Comment by nwhitmont** [comment]
What can I do to help move this forward?

**Comment by phated** [comment]
@nwhitmont the work is happening at https://github.com/gulpjs/vinyl-fs/pull/254

**Comment by phated** [comment]
We've wrapped up the symlink/junction work.  There's just some documentation/rebasing/cleanup work to do on vinyl-fs before the 3.0 release.

If you are interested in this stuff, please go try out the master branch and give us feedback - there are some **big** changes over there.

**Comment by phated** [comment]
Documentation has been finalized.  Rebase has been completed but it needs review.  Check out https://github.com/gulpjs/vinyl-fs/issues/284 if you are interested in reviewing.

**Comment by phated** [comment]
Based on the reactions, I expected more review/feedback on the rebase :frowning_face: 

Anyway, 3.0.0 has been published.  Changelog at https://github.com/gulpjs/vinyl-fs/releases/tag/v3.0.0

**Comment by CKGrafico** [comment]
Thanks for your awesome job @phated

**Comment by mcdado** [comment]
I tried to have a look but it was a bit overwhelming not knowing anything of the internals.

I second @CKGrafico, thank you and the whole team!
